module.exports = {
    USER_CONNECTED: "USER_CONNECTED",
    MESSAGE_RECIEVED: "MESSAGE_RECIEVED",
    MESSAGE_SENT: "MESSAGE_SENT",
    SEARCHING: "SEARCHING",
    FOUND: "FOUND",
    GAME_STATUS: "GAME_STATUS",
    GAME_MESSAGE: "GAME_MESSAGE",
    NEW_GAME: "NEW_GAME",
    ROOM: "ROOM",
    BACK: "BACK",
    RESTART: "RESTART",
    PLUS: "PLUS",
    ANIMATION: "ANIMATION"
}